"""
SICP Digital Circuit Simulator package.

Faithful Python implementation of the event-driven digital circuit simulator
from Structure and Interpretation of Computer Programs (SICP), Section 3.3.4,
with optional SimPy Discrete-Event Simulation engine extensions.
"""

from circuit_sim.agenda import (
    Agenda,
    TimeSegment,
    add_to_agenda,
    after_delay,
    current_time,
    empty_agenda,
    first_agenda_item,
    get_current_time,
    get_default_agenda,
    make_agenda,
    make_time_segment,
    propagate,
    remove_first_agenda_item,
    reset_default_agenda,
    segment_queue,
    segment_time,
    set_current_time,
    set_default_agenda,
)
from circuit_sim.circuits import (
    demultiplexer,
    full_adder,
    half_adder,
    multiplexer,
    ripple_carry_adder,
)
from circuit_sim.nbit import (
    alu,
    bus_to_int,
    n_bit_and,
    n_bit_and_bit,
    n_bit_mux,
    n_bit_not,
    n_bit_or,
    n_bit_register,
    n_bit_xor,
    or_reduce,
)
from circuit_sim.delays import DEFAULT_DELAYS, Delays
from circuit_sim.gates import (
    AndGate,
    Inverter,
    NandGate,
    NorGate,
    OrGate,
    PrimitiveFunctionBox,
    XorGate,
    and_gate,
    compound_or_gate,
    inverter,
    logical_and,
    logical_nand,
    logical_nor,
    logical_not,
    logical_or,
    logical_xor,
    nand_gate,
    nor_gate,
    or_gate,
    xor_gate,
)
from circuit_sim.probe import (
    ProbeEvent,
    ProbeRecorder,
    make_probe_recorder,
    probe,
)
from circuit_sim.queue import (
    Queue,
    delete_queue,
    empty_queue,
    front_queue,
    insert_queue,
    make_queue,
)
from circuit_sim.sequential import (
    binary_counter,
    d_flip_flop,
    d_latch,
    sr_latch,
    t_flip_flop,
)
from circuit_sim.simpy_agenda import (
    SIMPY_AVAILABLE,
    SimPyAgenda,
    clock_generator,
    make_realtime_agenda,
    make_simpy_agenda,
    pulse_generator,
    signal_schedule,
)
from circuit_sim.wire import (
    Wire,
    add_action,
    call_each,
    get_bus_values,
    get_signal,
    get_wire_name,
    make_bus,
    make_wire,
    set_bus_values,
    set_signal,
)

__all__ = [
    # Wire
    "Wire",
    "make_wire",
    "get_signal",
    "set_signal",
    "add_action",
    "get_wire_name",
    "call_each",
    "make_bus",
    "get_bus_values",
    "set_bus_values",
    # Queue
    "Queue",
    "make_queue",
    "empty_queue",
    "front_queue",
    "insert_queue",
    "delete_queue",
    # Agenda
    "Agenda",
    "TimeSegment",
    "make_agenda",
    "make_time_segment",
    "segment_time",
    "segment_queue",
    "empty_agenda",
    "current_time",
    "get_current_time",
    "set_current_time",
    "add_to_agenda",
    "first_agenda_item",
    "remove_first_agenda_item",
    "after_delay",
    "propagate",
    "get_default_agenda",
    "set_default_agenda",
    "reset_default_agenda",
    # SimPy Integration
    "SIMPY_AVAILABLE",
    "SimPyAgenda",
    "make_simpy_agenda",
    "make_realtime_agenda",
    "clock_generator",
    "pulse_generator",
    "signal_schedule",
    # Delays
    "Delays",
    "DEFAULT_DELAYS",
    # Logic & Gates
    "logical_not",
    "logical_and",
    "logical_or",
    "logical_nand",
    "logical_nor",
    "logical_xor",
    "inverter",
    "and_gate",
    "or_gate",
    "compound_or_gate",
    "nand_gate",
    "nor_gate",
    "xor_gate",
    "PrimitiveFunctionBox",
    "Inverter",
    "AndGate",
    "OrGate",
    "NandGate",
    "NorGate",
    "XorGate",
    # Combinational Circuits
    "half_adder",
    "full_adder",
    "ripple_carry_adder",
    "multiplexer",
    "demultiplexer",
    # N-bit datapath
    "n_bit_not",
    "n_bit_and",
    "n_bit_or",
    "n_bit_xor",
    "n_bit_and_bit",
    "n_bit_mux",
    "or_reduce",
    "n_bit_register",
    "alu",
    "bus_to_int",
    # Sequential Circuits
    "sr_latch",
    "d_latch",
    "d_flip_flop",
    "t_flip_flop",
    "binary_counter",
    # Probe
    "probe",
    "ProbeEvent",
    "ProbeRecorder",
    "make_probe_recorder",
]
